/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Mp3PlayerState {
  songTitle: string;
  genre: string;
  volume: number;
  isPlaying: boolean;
  loopOne: boolean;
  menuTitle: string;
  menu: unknown;
}
