/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface TabState {
  title: string;
  body: string;
  color: string;
  visibleColor: ColourState;
  id: number;
}
export interface ColourState {
  r: number;
  g: number;
  b: number;
}
