/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CustomImageState {
  ImageURL: string;
  ImageSecondaryURL: string;
  /**
   * Holds the scaled size of the object based on the image dimensions.
   */
  WidthScale: string;
  CustomDice: CustomDiceState;
  CustomToken: CustomTokenState;
  CustomJigsawPuzzle: CustomJigsawPuzzleState;
  CustomTitle?: CustomTileState;
}
export interface CustomDiceState {
  Type: unknown;
}
export interface CustomTokenState {
  Thickness: number;
  MergeDistancePixels: number;
  Stackable: boolean;
}
export interface CustomJigsawPuzzleState {
  NumPuzzlePieces?: number;
  ImageOnBoard: boolean;
}
export interface CustomTileState {
  /**
   * 0 = Plastic, 1 = Wood, 2 = Metal, 3 = Cardboard
   */
  Type: 0 | 1 | 2 | 3;
  Thickness: number;
  Stackable: boolean;
  Stretch: boolean;
}
