/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * http://docs.unity3d.com/ScriptReference/HingeJoint.html
 */
export interface JointHingeState {
  UseLimits: boolean;
  /**
   * Limit of angular rotation on the hinge joint. http://docs.unity3d.com/ScriptReference/JointLimits.html.
   */
  Limits: {
    [k: string]: unknown;
  };
  UseMotor: boolean;
  /**
   * Limit of angular rotation on the hinge joint. The motor will apply a force up to a maximum force to achieve the target velocity in degrees per second. http://docs.unity3d.com/ScriptReference/JointMotor.html.
   */
  Motor: {
    [k: string]: unknown;
  };
  UseSpring: boolean;
  /**
   * The spring attempts to reach a target angle by adding spring and damping forces. http://docs.unity3d.com/ScriptReference/JointSpring.html.
   */
  Spring: {
    [k: string]: unknown;
  };
}
