/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface VectorLineState {
  points3: VectorState[];
  color: ColourState;
  thickness: number;
  rotation: VectorState;
  loop?: boolean | null;
  square?: boolean | null;
}
export interface VectorState {
  x: number;
  y: number;
  z: number;
}
export interface ColourState {
  r: number;
  g: number;
  b: number;
}
