/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface RigidbodyState {
  /**
   * The mass of the object (arbitrary units). You should not make masses more or less than 100 times that of other Rigidbodies.
   */
  Mass: number;
  /**
   * How much air resistance affects the object when moving from forces. 0 means no air resistance, and infinity makes the object stop moving immediately.
   */
  Drag: number;
  /**
   * How much air resistance affects the object when rotating from torque. 0 means no air resistance. Note that you cannot make the object stop rotating just by setting its Angular Drag to infinity.
   */
  AngularDrag: number;
  /**
   * If enabled, the object is affected by gravity.
   */
  UseGravity: boolean;
}
