/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * http://docs.unity3d.com/ScriptReference/FixedJoint.html
 */
export type JointFixedState = JointState;

/**
 * http://docs.unity3d.com/ScriptReference/Joint.html
 */
export interface JointState {
  /**
   * A reference to another rigidbody this joint connects to.
   */
  ConnectedBodyGUID: string;
  /**
   * Enable collision between bodies connected with the joint.
   */
  EnableCollision: boolean;
  Axis: VectorState;
  Anchor: VectorState1;
  /**
   * The force that needs to be applied for this joint to break.
   */
  BreakForce: number;
  /**
   * The torque that needs to be applied for this joint to break.
   */
  BreakTorgue: number;
}
/**
 * The Direction of the axis around which the body is constrained.
 */
export interface VectorState {
  x: number;
  y: number;
  z: number;
}
/**
 * The Position of the anchor around which the joints motion is constrained.
 */
export interface VectorState1 {
  x: number;
  y: number;
  z: number;
}
