/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * http://docs.unity3d.com/ScriptReference/SpringJoint.html
 */
export interface JointSpringState {
  /**
   * The damper force used to dampen the spring force
   */
  Damper: number;
  /**
   * The maximum distance between the bodies relative to their initial distance.
   */
  MaxDistance: number;
  /**
   * The minimum distance between the bodies relative to their initial distance.
   */
  MinDistance: number;
  /**
   * The spring force used to keep the two objects together.
   */
  Spring: number;
}
