/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CustomDeckState {
  FaceURL: string;
  BackURL: string;
  NumWidth?: number | null;
  NumHeight?: number | null;
  /**
   * Back of cards becames the hidden card when in a hand.
   */
  BackIsHidden: boolean;
  /**
   * Each back is a unique card just like the front.
   */
  UniqueBack: boolean;
}
