/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface TurnsState {
  Enable: boolean;
  /**
   * Auto = turn order is based on positioning of hands on around table, Custom = turn order is based on an user color list.
   */
  Type: "Auto" | "Customs";
  TurnOrder: string[];
  Reverse: boolean;
  SkipEmpty: boolean;
  DisableInteractions?: boolean;
  PassTurns: boolean;
  TurnColor: string;
}
