/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface HandsState {
  LightIntensity: number;
  LightColor: ColourState;
  AmbientIntensity: number;
  /**
   * Background = ambient light comes from the background, Gradient = ambient light comes from the three ambient colors.
   */
  AmbientType: "Background" | "Gradient";
  AmbientSkyColor: ColourState1;
  AmbientEquatorColor: ColourState2;
  AmbientGroundColor: ColourState3;
  ReflectionIntensity: number;
  LutIndex: number;
  LutContribution: number;
  /**
   * LUT 256x16
   */
  LutURL: string;
}
export interface ColourState {
  r: number;
  g: number;
  b: number;
}
export interface ColourState1 {
  r: number;
  g: number;
  b: number;
}
export interface ColourState2 {
  r: number;
  g: number;
  b: number;
}
export interface ColourState3 {
  r: number;
  g: number;
  b: number;
}
